### ISSUE TITLE
Add Read screen

### ISSUE THREAD

**Issue by MatRos-sf** [MatRos-sf/ShadowingApp#5]
https://www.youtube.com/watch?v=oc09fkWZVOQ

Aby dodać możliwość przewijania do BoxLayout, musisz umieścić go w ScrollView, który pozwala na przewijanie zawartości, gdy jest za duża, by zmieścić się na ekranie. ScrollView jest specjalnym widgetem, który umożliwia przewijanie w poziomie lub w pionie.
Jak dodać przewijanie do BoxLayout:

    Umieść BoxLayout wewnątrz ScrollView.
    Ustaw odpowiednią wielkość i kierunek przewijania (pionowy lub poziomy).

Przykład:
W pliku .kv:

```
<MainScreen>:
    ScrollView:
        BoxLayout:
            orientation: 'vertical'
            size_hint_y: None  # Ważne, by BoxLayout nie miał domyślnej wysokości
            height: self.minimum_height  # Dostosowanie wysokości do zawartości
            padding: 10
            spacing: 10
            
            Button:
                text: 'Button 1'
            
            Button:
                text: 'Button 2'
            
            Button:
                text: 'Button 3'
            
            # Możesz dodać więcej widgetów, aby zobaczyć przewijanie
            Button:
                text: 'Button 4'
            
            Button:
                text: 'Button 5'
            
            Button:
                text: 'Button 6'
            
            # Dodaj tyle przycisków, ile chcesz, aby sprawdzić przewijanie
```
Wyjaśnienie:
ScrollView jest kontenerem, który umożliwia przewijanie zawartości w pionie lub poziomie.
BoxLayout ma ustawioną size_hint_y na None i height na self.minimum_height, aby dynamicznie dostosowywał swoją wysokość do liczby elementów. Gdy elementy przekroczą dostępną przestrzeń, pojawi się pasek przewijania.

W ten sposób zawartość BoxLayout w ScrollView będzie przewijana, gdy elementy będą zajmować więcej miejsca, niż jest dostępne na ekranie.
